# Generated by Django 5.2 on 2025-06-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The best offer', max_length=100)),
                ('subtitle', models.CharField(default='for your business', max_length=100)),
                ('description', models.TextField(default='Join the Baobyte platform and take your projects to the next level. We care about security, style, and performance.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
        ),
    ]
