# Generated by Django 5.2 on 2025-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_google_login', models.BooleanField(default=False, help_text='Enable login with Google')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
