# Generated by Django 5.2 on 2025-06-09 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_terms_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used for password reset', max_length=254)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('successful', models.BooleanField(default=False, help_text='Was the password reset completed?')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Originating IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client device or browser string', null=True)),
            ],
        ),
    ]
