# Generated by Django 5.2 on 2025-06-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetlog',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetlog',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetlog',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordresetlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetlog',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
