# Generated by Django 5.2 on 2025-08-21 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetlog_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Aliad@'), ('client', 'Cliente'), ('admin', 'Administrador')], default='client', help_text='Tipo de usuario: empleada doméstica, cliente o admin', max_length=10),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_payment_method', models.CharField(blank=True, help_text='Reference ID for preferred payment method', max_length=50)),
                ('billing_address', models.CharField(blank=True, help_text='Optional billing address (used for invoices)', max_length=255)),
                ('subscription_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('services_offered', models.TextField(blank=True, help_text='Comma-separated list of services offered (e.g. limpieza, cocina, niños)')),
                ('work_area', models.CharField(blank=True, help_text='Preferred work area or neighborhood', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Used to locate the employee on a map', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('documents', models.FileField(blank=True, help_text='Optional documents for identity or references', null=True, upload_to='documents/')),
                ('rating', models.FloatField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
